### ISSUE TITLE
Cli rm builder not adding updated validated_config call inside rmodule_fact.py

### ISSUE THREAD

**Issue by ashwini-mhatre** [ansible-network/cli_rm_builder#14]
##### SUMMARY

cli-rm-builder not adding new validate_config call inside fact.py

example:
it should add 
```
params = utils.remove_empties(
            prefix_lists_parser.validate_config(
                self.argument_spec, {"config": obj}, redact=True
            )
        )
```
this line inside prefix_list_facts.py now its adding

```
params = utils.remove_empties(
            utils.validate_config(self.argument_spec, {"config": obj})
        )
```
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by NilashishC** [comment]
The updated line has been added to the template. Ref: https://github.com/ansible-network/cli_rm_builder/blob/main/roles/scaffold_resource_module/templates/module_utils/network_os/facts/resource/resource.py.j2#L60-L62.

Are you on the latest builder?

**Comment by NilashishC** [comment]
Closing this as discussed over Slack.
